const fs = require('fs');

/**
 * This build script transforms an Excel spreadsheet containing your master
 * chemical database into a JavaScript module. It uses the popular
 * `xlsx` package to read `.xlsx` files. Before running this script
 * you must install the dependency in your project (e.g. `npm install xlsx`).
 *
 * Similar to the CSV builder, this script treats the Excel file as the
 * authoritative source of chemical data and generates a `chemicals.js`
 * file in ES module format. If the structure of your spreadsheet
 * changes (e.g. column names), adjust the `transformRow` function
 * accordingly.
 */

// Attempt to require the xlsx library. If it is not installed, provide
// a friendly error message with installation instructions.
let XLSX;
try {
  XLSX = require('xlsx');
} catch (err) {
  console.error(
    'Missing dependency: The xlsx library is required to parse Excel files.\n' +
      'Install it by running `npm install xlsx` in your project root, then re‑run this script.'
  );
  process.exit(1);
}

// Path to the input XLSX. Overridable via environment variable.
const INPUT_XLSX = process.env.INPUT_XLSX || 'Chemicals_Master_Tight_v1.xlsx';

// Path to the output JS. Overridable via environment variable.
const OUTPUT_JS = process.env.OUTPUT_JS || 'chemicals.js';

/**
 * Attempt to coerce a value to a number. Returns null for empty strings
 * and leaves non‑numeric strings untouched.
 *
 * @param {any} value
 * @returns {number|null|any}
 */
function toNumber(value) {
  if (value == null || value === '') return null;
  const num = Number(value);
  return Number.isFinite(num) ? num : value;
}

/**
 * Custom row transform. Maps the raw row into the structure used by
 * your application. Adjust this function to reflect your spreadsheet’s
 * column names and the desired output format.
 *
 * @param {Object} row A single row object parsed by xlsx.utils.sheet_to_json.
 * @returns {Object}
 */
function transformRow(row) {
  return {
    id: row.id || row.ID || null,
    name: row.name || row.Product || row.Name || null,
    activeIngredient: row.activeIngredient || row['Active Ingredient'] || null,
    productType: row.productType || row['Product Type'] || null,
    moaGroup: row.moaGroup || row.FRAc || row.IRAC || row.MOA || null,
    targetPests: row.targetPests || row['Target Pests'] || null,
    applicationSites: row.applicationSites || row['Application Sites'] || null,
    defaultRatePerGallon: toNumber(
      row.defaultRatePerGallon || row['Rate Per Gallon'] || row['Default Rate Per Gallon']
    ),
    defaultGranularRatePerThousandSqFt: toNumber(
      row.defaultGranularRatePerThousandSqFt ||
        row['Granular Rate Per Thousand Sq Ft'] ||
        row['Granular Rate']
    ),
    reiHours: toNumber(row.reiHours || row.REI || row['REI Hours'] || row['REI (hrs)']),
    mixRate: row.mixRate || row['Mix Rate'] || null,
    epaNumber: row.epaNumber || row['EPA Number'] || null,
    compatibility: (row.compatibility || row['Compatibility'] || '')
      ?.toString()
      .split(/[;,]/)
      .map((s) => s.trim())
      .filter((s) => s.length > 0),
    notes: row.notes || row.Notes || null,
    // Preserve all original keys for reference under raw
    raw: row,
  };
}

function build() {
  // Check that the input file exists
  if (!fs.existsSync(INPUT_XLSX)) {
    console.error(`Input file not found: ${INPUT_XLSX}`);
    process.exit(1);
  }
  // Read the workbook
  const workbook = XLSX.readFile(INPUT_XLSX, { cellDates: true });
  const sheetName = workbook.SheetNames[0];
  const sheet = workbook.Sheets[sheetName];
  // Parse rows; defval: null ensures empty cells map to null
  const rows = XLSX.utils.sheet_to_json(sheet, { defval: null });
  const transformed = rows.map(transformRow);
  // Write a file that works in both browser and Node environments. When loaded
  // in a browser via a regular <script> tag, it assigns the `chemicals` array
  // to the global `window` so existing code can access it. When required in
  // Node (e.g. for testing or server‑side code), it exports the array via
  // `module.exports`. Do not include ES module syntax such as `export`
  // statements here; doing so would break loading in non‑module script tags.
  const chemicalsJson = JSON.stringify(transformed, null, 2);
  const outputLines = [];
  outputLines.push(`// This file is auto‑generated by scripts/buildChemicalsFromExcel.js.`);
  outputLines.push(`// Do not edit by hand. Modify ${INPUT_XLSX} and run the script to regenerate.`);
  outputLines.push(`const chemicals = ${chemicalsJson};`);
  // Assign to window for browser usage
  outputLines.push(`if (typeof window !== 'undefined') { window.chemicals = chemicals; }`);
  // Export for CommonJS environments (Node)
  outputLines.push(`if (typeof module !== 'undefined' && module.exports) { module.exports = chemicals; }`);
  // Write the joined lines to the output JS file
  fs.writeFileSync(OUTPUT_JS, outputLines.join('\n') + '\n', 'utf8');
  console.log(`Generated ${OUTPUT_JS} from ${INPUT_XLSX}. Total records: ${transformed.length}`);
}

build();